- mysql_user: name={{ db_username }} password={{ db_password }} priv=*.*:ALL,GRANT state=present

- mysql_db: name={{ db_name }} encoding=utf8 login_user={{ db_username }} login_password={{ db_password }} state=present

- git: repo=git://github.com/nicolasblanco/sharetribe.git
       dest=/home/deploy/sharetribe
       version=puma

- mysql_db: name={{ db_name }}
            login_user={{ db_username }}
            login_password={{ db_password }}
            state=import target=/home/deploy/sharetribe/db/structure.sql
