- name: create mysql root pass
  command: /usr/bin/openssl rand -base64 16
  register: mysql_root_passwd

- name: register mysql root pass
  shell: echo mysql-server mysql-server/root_password password {{ mysql_root_passwd.stdout }} | sudo /usr/bin/debconf-set-selections

- name: register mysql root pass confirm
  shell: echo mysql-server mysql-server/root_password_again password {{ mysql_root_passwd.stdout }} | sudo /usr/bin/debconf-set-selections

- name: MySQL | Install server
  apt: pkg={{ item }} state=latest
  with_items:
    - mysql-server

- name: MySQL | Install client and libs
  apt: pkg={{ item }} state=installed
  with_items:
    - mysql-client
    - python-mysqldb

- name: copy user my.cnf file with root passwd credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600

- name: delete anonymous mysql user
  mysql_user: name="" state=absent

- name: remove mysql test database
  mysql_db: name=test state=absent
